---

# Values from IBM High Performance Computing - Linux System Tuning Recommendations
# https://www.ibm.com/developerworks/community/wikis/home?lang=en#!/wiki/Welcome%20to%20High%20Performance%20Computing%20%28HPC%29%20Central/page/Linux%20System%20Tuning%20Recommendations

- name: Load the conntrack_ipv4 module (needed for the conntrack setting update)
  become: true
  command: /sbin/modprobe nf_conntrack_ipv4

- name: Load the conntrack module (needed for the conntrack setting update)
  become: true
  command: /sbin/modprobe nf_conntrack

- name: Add the nf_conntrack_ipv4 module to /etc/modules (in case of reboot)
  lineinfile:
    dest: /etc/modules
    line: nf_conntrack_ipv4
    state: present

- name: Add the nf_conntrack module to /etc/modules (in case of reboot)
  lineinfile:
    dest: /etc/modules
    line: nf_conntrack
    state: present

#: Update sysctl.conf tuning
- sysctl:
    name: net.ipv4.tcp_max_tw_buckets
    value: 1440000
    state: present
    reload: no

- sysctl:
    name: net.ipv4.tcp_tw_reuse
    value: 1
    state: present
    reload: no

- sysctl:
    name: net.ipv4.ip_local_port_range
    value: "18000 65535"
    state: present
    reload: no

- sysctl:
    name: net.netfilter.nf_conntrack_tcp_timeout_time_wait
    value: 3
    state: present
    reload: no

- sysctl:
    name: net.ipv4.tcp_fin_timeout
    value: 3
    state: present
    reload: no

- sysctl:
    name: net.ipv4.tcp_rmem
    value: "4096 87380 16777216"
    state: present
    reload: no

- sysctl:
    name: net.ipv4.tcp_wmem
    value: "4096 87380 16777216"
    state: present
    reload: no

- sysctl:
    name: net.ipv4.tcp_mem
    value: "16777216 16777216 16777216"
    state: present
    reload: no

- sysctl:
    name: net.core.rmem_default
    value: 16777216
    state: present
    reload: no

- sysctl:
    name: net.core.rmem_max
    value: 16777216
    state: present
    reload: no

- sysctl:
    name: net.core.wmem_default
    value: 16777216
    state: present
    reload: no

- sysctl:
    name: net.core.wmem_max
    value: 16777216
    state: present
    reload: no

- sysctl:
    name: net.core.optmem_max
    value: 16777216
    state: present
    reload: no

- sysctl:
    name: net.ipv4.tcp_sack
    value: 0
    state: present
    reload: no

- sysctl:
    name: net.ipv4.tcp_dsack
    value: 0
    state: present
    reload: no

- sysctl:
    name: net.ipv4.tcp_timestamps
    value: 0
    state: present
    reload: no

- sysctl:
    name: net.ipv4.tcp_slow_start_after_idle
    value: 0
    state: present
    reload: no

- sysctl:
    name: net.ipv4.tcp_window_scaling
    value: 1
    state: present
    reload: no

- sysctl:
    name: net.ipv4.route.flush
    value: 1
    state: present
    reload: yes
