[iks]
endpoint = "CARRIER_iks_endpoint_CARRIER"

[satlink]
endpoint = "https://api.link.satellite.test.cloud.ibm.com"

[vpc]
endpoint = "https://us-south.iaas.cloud.ibm.com"

[ibmcloud]
iam_endpoint = "https://iam.test.cloud.ibm.com"
username = "KEY_armada_performance_functional_id_KEY"
account_id = "KEY_armada_performance_account_id_KEY"

infra_iam_endpoint = "https://iam.cloud.ibm.com"

classic_infra_username = "KEY_PROD_GLOBAL_ARMPERF_SOFTLAYER_1540207_USERID_KEY"
