

apiVersion: v1
kind: Service
metadata:
  name: netperf-lb-public
  labels:
    app: netperf-lb
spec:
  ports:
  - name: iperf
    port: 5201
    targetPort: 5201
  - name: ssh
    port: 22
    targetPort: 22
  type: LoadBalancer
  sessionAffinity: ClientIP
  selector:
    app: netperf-lb

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: netperf-lb
spec:
  serviceName: "netperf-lb"
  replicas: 2
  template:
    metadata:
      labels:
        app: netperf-lb
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
        - name: netperf-lb
          image: stg.icr.io/armada_performance/netperf:latest
          ports:
          - containerPort: 5201
            name: iperf
            protocol: TCP
          - containerPort: 22
            name: ssh
            protocol: TCP
      imagePullSecrets:
        - name: perf.secret
