
apiVersion: v1
kind: Service
metadata:
  name: netperf-np-public
  labels:
    app: netperf-np
spec:
  ports:
  - name: iperf
    port: 5201
  - name: ssh
    port: 22
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    app: netperf-np

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: netperf-np
spec:
  serviceName: "netperf-np"
  replicas: 2
  template:
    metadata:
      labels:
        app: netperf-np
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
        - name: netperf-np
          image: stg.icr.io/armada_performance/netperf:latest
          ports:
          - containerPort: 5201
            name: iperf
            protocol: TCP
          - containerPort: 22
            name: ssh
            protocol: TCP
      imagePullSecrets:
        - name: perf.secret
