
apiVersion: v1
kind: Service
metadata:
  name: netperf-ci
  labels:
    app: netperf-ci
spec:
  ports:
  - name: iperf
    port: 5201
  - name: ssh
    port: 22
  clusterIP: None
  selector:
    app: netperf-ci

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: netperf-ci
spec:
  serviceName: "netperf-ci"
  replicas: 2
  template:
    metadata:
      labels:
        app: netperf-ci
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
        - name: netperf-ci
          image: stg.icr.io/armada_performance/netperf:latest
          ports:
          - containerPort: 5201
            name: iperf
            protocol: TCP
          - containerPort: 22
            name: ssh
            protocol: TCP
