# Default values for iperfserver
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
podCount: 1
port: 30521
id: 1
image:
  registry: stg.icr.io
  name: armada_performance/iperf
  tag: latest
  pullPolicy: Always
lb:
    zone: dal09
    vlanID: 2263903
    port: 40521
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  #requests:
  #  cpu: 100m
  #  memory: 128Mi
