#!/bin/bash
# ******************************************************************************
# * Licensed Materials - Property of IBM
# * IBM Cloud Kubernetes Service, 5737-D43
# * (C) Copyright IBM Corp. 2020 All Rights Reserved.
# * US Government Users Restricted Rights - Use, duplication or
# * disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
# ******************************************************************************

# This script extracts the results from log file generated by getEndUserAuthorizationTimes.sh
# See getEndUserAuthorizationTimes.sh for details on running the tests
# The first measurement isn't included in the average

if [[ $# -ne 1 ]]; then
	echo "ERROR: Must specify results file"
	exit 1
fi
RESULTS_FILE=$1

totalMetrics=$(grep "^real" ${RESULTS_FILE} | wc -l)
if [[ ${totalMetrics} -ne 22 ]]; then
	echo "ERROR: Expected 10 metrics, but found ${totalMetrics}"
	exit 1
fi
adminFirst=$(grep "^real" ${RESULTS_FILE} | head -1 | awk '{print $2}' | sed -e "s/0m//g" -e "s/s$//g" | awk '{s+=$1; cnt+=1} END {print s/cnt}')
adminAverage=$(grep "^real" ${RESULTS_FILE} | head -11 | tail -10 | awk '{print $2}' | sed -e "s/0m//g" -e "s/s$//g" | awk '{s+=$1; cnt+=1} END {print s/cnt}')
userFirst=$(grep "^real" ${RESULTS_FILE} | head -12 | tail -1 | awk '{print $2}' | sed -e "s/0m//g" -e "s/s$//g" | awk '{s+=$1; cnt+=1} END {print s/cnt}')
userAverage=$(grep "^real" ${RESULTS_FILE} | tail -10 | awk '{print $2}' | sed -e "s/0m//g" -e "s/s$//g" | awk '{s+=$1; cnt+=1} END {print s/cnt}')

echo "admin:first,admin:avg,non-admin:min,non-admin:avg"
echo "${adminFirst},${adminAverage},${userFirst},${userAverage}"
