FROM websphere-liberty:21.0.0.12-kernel-java8-ibmjava

# Install additional apps as root user
USER 0
RUN apt-get update && apt-get upgrade -y && apt-get clean -y

# Switch back to non-root user
USER 1001
COPY --chown=1001:0 server.xml /config/server.xml
COPY --chown=1001:0 proxytai /config/proxytai
COPY --chown=1001:0 jvm.options /config/jvm.options
COPY --chown=1001:0 target/OLB-1.0.0-SNAPSHOT.war /config/apps/

# This script will add the requested XML snippets, grow image to be fit-for-purpose and apply interim fixes
RUN configure.sh
