apiVersion: v1
name: incluster-apiserver-target
description: A Helm chart for installing resources used by incluster apiserver load test
version: 1.0.0
home: https://github.ibm.com/alchemy-containers/armada-performance/incluster-apiserver
sources:
  - https://github.ibm.com/alchemy-containers/armada-performance/incluster-apiserver
appVersion: 1.0
