apiVersion: v1
kind: Service
metadata:
  # This service is meant to be used by clients of the database. It exposes a ClusterIP that will
  # automatically load balance connections to the different database pods.
  name: etcd-slnfs-public
  labels:
    app: etcd-slnfs 
spec:
  ports:
  - port: 2379
    targetPort: 2379
    name: client 
  - port: 2380
    targetPort: 2380
    name: peer
  type: NodePort 
  selector:
    app: etcd-slnfs 
---

apiVersion: v1
kind: Service
metadata:
  name: etcd-slnfs
  labels:
    app: etcd-slnfs
spec:
  ports:
    - name: peer
      port: 2380
    - name: client
      port: 2379
  clusterIP: None
 # type: NodePort
  selector:
    app: etcd-slnfs

---

apiVersion: v1
kind: Secret
metadata:
  name: etcd-slnfs
data:
  # create by `echo -n "MyEtcdToken" | base64"
  token: TXlFdGNkVG9rZW4=

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: etcd-slnfs
spec:
  serviceName: "etcd-slnfs"
  replicas: 3
  template:
    metadata:
      labels:
        app: etcd-slnfs
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
        - name: etcd-slnfs
          image: quay.io/coreos/etcd:v3.1.5
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ETCD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ETCD_INITIAL_CLUSTER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: etcd-slnfs
                  key: token
            - name: ETCD_DATA_DIR
              value: "/data/$(ETCD_NAME)"
            - name: ETCD_INITIAL_CLUSTER
              value: "etcd-slnfs-0=http://etcd-slnfs-0.etcd-slnfs.$(POD_NS).svc.cluster.local:2380,etcd-slnfs-1=http://etcd-slnfs-1.etcd-slnfs.$(POD_NS).svc.cluster.local:2380,etcd-slnfs-2=http://etcd-slnfs-2.etcd-slnfs.$(POD_NS).svc.cluster.local:2380"
            - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
              value: "http://$(ETCD_NAME).etcd-slnfs.$(POD_NS).svc.cluster.local:2380"
            - name: ETCD_LISTEN_PEER_URLS
              value: "http://$(POD_IP):2380"
            - name: ETCD_LISTEN_CLIENT_URLS
              value: "http://$(POD_IP):2379"
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: "http://$(ETCD_NAME).etcd-slnfs.$(POD_NS).svc.cluster.local:2379"
            - name: ETCD_QUOTA_BACKEND_BYTES
              value: "8589934592"
            - name: ETCD_AUTO_COMPACTION_RETENTION
              value: "1"
          ports:
            - name: peer
              containerPort: 2380
            - name: client
              containerPort: 2379
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: etcd_100Gi_n1
      volumes:
        - name: config
          emptyDir:
            medium: Memory
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Gi
