<F5>apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-etcd-0
spec:
  capacity:
    storage: "100Gi"
  accessModes:
    - ReadWriteOnce
  nfs:
    server: "10.130.231.171"
    path: "/opt/etcd_containers/data-etcd-0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-etcd-1
spec:
  capacity:
    storage: "100Gi"
  accessModes:
    - ReadWriteOnce
  nfs:
    server: "10.130.231.171"
    path: "/opt/etcd_containers/data-etcd-1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-etcd-2
spec:
  capacity:
    storage: "100Gi"
  accessModes:
    - ReadWriteOnce
  nfs:
    server: "10.130.231.171"
    path: "/opt/etcd_containers/data-etcd-2"
