FROM websphere-liberty:22.0.0.5-kernel-java8-ibmjava

COPY src/main/liberty/config/server.xml /config/server.xml
COPY src/main/liberty/config/server.env /config/server.env
COPY src/main/liberty/config/jvm.options /config/jvm.options
COPY target/acmeair-flightservice-java-3.0.war /config/apps/

USER 0
RUN apt-get update && apt-get upgrade -y && apt-get clean -y
RUN chown 1001:0 /config/server.xml
RUN chown 1001:0 /config/server.env
# The following enable a javacore to be generated if JVM is hitting 100% CPU
RUN echo "-Xdump:java:none:events=user" >> /config/jvm.options
RUN echo "-Xdump:java:events=user,request=exclusive+prepwalk+preempt" >> /config/jvm.options
RUN chown 1001:0 /config/jvm.options
RUN chown 1001:0 /config/apps/acmeair-flightservice-java-3.0.war
USER 1001

RUN configure.sh || if [ $? -ne 22 ]; then exit $?; fi
