apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpperf
spec:
  replicas: 3 
  template:
    metadata:
      labels:
        app: httpperf
    spec:
      containers:
        - name: httpperf0
          image: "stg.icr.io/armada_performance_stage1/httpperf0:latest"
          ports:
            - containerPort: 8080
            - containerPort: 8443
        - name: httpperf1
          image: "stg.icr.io/armada_performance_stage1/httpperf1:latest"
          ports:
            - containerPort: 8081
            - containerPort: 8444
        - name: httpperf2
          image: "stg.icr.io/armada_performance_stage1/httpperf2:latest"
          ports:
            - containerPort: 8082
            - containerPort: 8445
---

apiVersion: v1
kind: Service
metadata:
  name: httpperf-lb-service
spec:
  type: LoadBalancer
  selector:
    app: httpperf
  ports:
   - protocol: TCP
     port: 30080
     targetPort: 8080
     name: http0
   - protocol: TCP
     port: 30081
     targetPort: 8081
     name: http1
   - protocol: TCP
     port: 30082
     targetPort: 8082
     name: http2
   - protocol: TCP
     port: 30043
     targetPort: 8443
     name: https0
   - protocol: TCP
     port: 30044
     targetPort: 8444
     name: https1
   - protocol: TCP
     port: 30045
     targetPort: 8445
     name: https2

---
