apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "pod-scaling.fullname" . }}
  labels:
    app: nginx
    chart: {{ template "pod-scaling.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: "{{ $.Values.image.registry }}{{ $.Values.image.name }}:{{ $.Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
{{ if .Values.restricted }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
      securityContext:
        runAsNonRoot: true
        runAsUser: 100001
{{ end }}
