apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.prefix }}-{{ .Chart.Name }}-sa
  namespace: {{ .Values.namespace }}
roleRef:
imagePullSecrets:
  - name: {{ .Values.pullSecretsName }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.prefix }}-{{ .Chart.Name }}-reader
  namespace: {{ .Values.namespace }}
roleRef:
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.prefix }}-{{ .Chart.Name }}-reader
  namespace: {{ .Values.namespace }}
roleRef:
subjects:
- kind: ServiceAccount
  name: {{ .Values.prefix }}-{{ .Chart.Name }}-sa
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole 
  name: {{ .Values.prefix }}-{{ .Chart.Name }}-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prefix }}-{{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
roleRef:
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: incluster-apiserver
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Values.prefix }}-{{ .Chart.Name }}-sa
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /incluster-apiserver
            - --throughput={{ .Values.parameters.throughput }}
            - --namespace={{ .Values.parameters.getNamespace }}
            - --runtime={{ .Values.parameters.runtime }}
{{ if .Values.parameters.disable_compression }}
            - --disable_compression
{{ end }}
{{ if .Values.restricted }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      securityContext:
        runAsNonRoot: true
        runAsUser: 100001
{{ end }}
