---
# Update Grafana which is installed on perf client 1-3

- name: install the deb file 
  become: true
  apt:
    deb: "https://dl.grafana.com/oss/release/grafana_{{ grafana_version }}_amd64.deb"
    state: present

- name: restart the grafana service
  service:
     name: grafana-server
     state: restarted
     enabled: yes    
  
