kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jmeter-master-rolebinding
  labels:
    app: jmeter-master
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: jmeter-master-role
  apiGroup: ""
