apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpperf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpperf
  template:
    metadata:
      labels:
        app: httpperf
    spec:
      imagePullSecrets:
      - name: performance-registry-token
      containers:
        - name: httpperf1
          image: "stg.icr.io/armada_performance_stage4/httpperf:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
            - containerPort: 443
          livenessProbe:
            httpGet:
              path: /hello
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 300
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 160
          readinessProbe:
            httpGet:
              path: /hello
              port: 8080
        - name: iperfserver1
          image: "stg.icr.io/armada_performance/iperf:latest"
          imagePullPolicy: IfNotPresent
          # default port is 5201
          args: ["-p 5201"]
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - "sleep 5; uname -a; ps -ef"
            failureThreshold: 3
            initialDelaySeconds: 300
            periodSeconds: 35
            successThreshold: 1
            timeoutSeconds: 160
        - name: iperfserver2
          image: "stg.icr.io/armada_performance/iperf:latest"
          imagePullPolicy: IfNotPresent
          args: ["-p 5202"]
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - "sleep 10; echo hello; ps -ef"
            failureThreshold: 3
            initialDelaySeconds: 300
            periodSeconds: 35
            successThreshold: 1
            timeoutSeconds: 160
        - name: iperfserver3
          image: "stg.icr.io/armada_performance/iperf:latest"
          imagePullPolicy: IfNotPresent
          args: ["-p 5203"]
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - "sleep 15; uname -a; ps -ef"
            failureThreshold: 3
            initialDelaySeconds: 300
            periodSeconds: 35
            successThreshold: 1
            timeoutSeconds: 160
        - name: iperfserver4
          image: "stg.icr.io/armada_performance/iperf:latest"
          imagePullPolicy: IfNotPresent
          args: ["-p 5204"]
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - "sleep 20; echo hello; ps -ef"
            failureThreshold: 3
            initialDelaySeconds: 300
            periodSeconds: 35
            successThreshold: 1
            timeoutSeconds: 160
        - name: iperfserver5
          image: "stg.icr.io/armada_performance/iperf:latest"
          imagePullPolicy: IfNotPresent
          args: ["-p 5205"]
          livenessProbe:
            httpGet:
              path: /hello
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 300
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 160

---

apiVersion: v1
kind: Service
metadata:
  name: httpperfserver1-np-service
spec:
  type: NodePort
  selector:
    app: httpperf
  ports:
   - name: http
     protocol: TCP
     port: 8080
     nodePort: HTTPPERF_NP_HTTP
   - name: https
     protocol: TCP
     port: 443
     nodePort: HTTPPERF_NP_HTTPS

---

apiVersion: v1
kind: Service
metadata:
  name: httpperf-lb-service
spec:
  type: LoadBalancer
  selector:
    app: httpperf
  ports:
   - protocol: TCP
     port: HTTPPERF_LB_HTTP
     targetPort: 8080
     name: http
   - protocol: TCP
     port: HTTPPERF_LB_HTTPS
     targetPort: 443
     name: https

---

apiVersion: v1
kind: Service
metadata:
  name: httpperf-ingress-service
spec:
  selector:
    app: httpperf
  ports:
   - protocol: TCP
     port: 8080

---
