apiVersion: v1
kind: Pod
metadata:
  labels:
    app: etcd
    etcd_node: etcdcm0
  name: cloud-mon-app
spec:
  containers:
  - command:
    - /usr/local/bin/etcd
    - --name
    - etcdcm0
    - --initial-advertise-peer-urls
    - http://etcdcm0:2380
    - --listen-peer-urls
    - http://0.0.0.0:2380
    - --listen-client-urls
    - http://0.0.0.0:2379
    - --advertise-client-urls
    - http://etcdcm0:2379
    - --initial-cluster
    - etcdcm0=http://etcdcm0:2380
    - --initial-cluster-state
    - new
    image: quay.io/coreos/etcd:v3.1.5
    name: etcdcm0
    ports:
    - containerPort: 2379
      name: client
      protocol: TCP
    - containerPort: 2380
      name: server
      protocol: TCP
  restartPolicy: Never
