apiVersion: ocs.ibm.io/v1
kind: OcsCluster
metadata:
 name: ocs-storagecluster
spec:
 monStorageClassName: ibmc-vpc-block-metro-10iops-tier
 monSize: 20Gi
 osdStorageClassName: ibmc-vpc-block-metro-10iops-tier
 osdSize: 4000Gi
 numOfOsd: 1
 billingType: advanced
 ocsUpgrade: false
 