- apiVersion: v1
  kind: policy
  metadata:
    name: deny-compose
  spec:
    egress:
    - action: deny
      protocol: tcp
      source: {}
      destination:
        net: 10.143.91.71/32
        ports: 
        - 15112
    order: 500
    selector: calico/k8s_ns in {'monitoring', 'armada'}
