# Default parameters that explores performance space given limited CPU.

# Number of seconds to run with a particular setting.
run_length_seconds: [600]
# Maximum QPS for dnsperf. dnsperf is self-pacing and will ramp request rate
# until requests are dropped. null means no limit.
max_qps: [null]
# File to take queries from. This is in dnsperf format.
query_file: ["service.txt"]
